config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView, RedirectView

urlpatterns = [
                  path("", RedirectView.as_view(url="/newsletters"), name="home"),
                  # Django Admin, use {% url 'admin:index' %}
                  path(settings.ADMIN_URL, admin.site.urls),
                  # User management
                  path("users/", include("infoparlamento.users.urls", namespace="users")),
                  path("accounts/", include("allauth.urls")),
                  # Your stuff: custom urls includes go here
                  path("newsletters/", include("infoparlamento.newsletter.urls", namespace="newsletter")),
                  path("privacy/", TemplateView.as_view(template_name="privacy.html"), name="privacy"),
                  path("cookie/", TemplateView.as_view(template_name="cookie.html"), name="cookie"),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('django-rq/', include('django_rq.urls'))
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

infoparlamento/newsletter/urls.py
from django.urls import path

from infoparlamento.newsletter import views
from infoparlamento.newsletter.views import (
    news_detail_view, news_search_view, newsletter_detail_view, news_pdf_view, newsletter_list_view
)

app_name = "newsletter"
urlpatterns = [
    path("", view=newsletter_list_view, name="newsletter_list"),
    path("<int:pk>/", view=newsletter_detail_view, name="newsletter_detail"),
    path("news/<int:pk>/", view=news_detail_view, name="news_detail"),
    path('news/<int:pk>/pdf/', view=news_pdf_view, name='news_pdf'),
    path("ricerca/", view=news_search_view, name="news_search"),
    path('admin/get_subtags/', views.get_subtags, name='get_subtags'),
]

infoparlamento/users/urls.py
from django.urls import path

from infoparlamento.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view, impersonate_user, stop_impersonation,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path('impersonate/<int:user_id>/', view=impersonate_user, name='impersonate-user'),
    path('stopimpersonation/', view=stop_impersonation, name='stop-impersonation'),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

infoparlamento/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField, ForeignKey, CASCADE, OneToOneField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from infoparlamento.newsletter.models import Customer


class User(AbstractUser):
    """
    Default custom user model for InfoParlamento.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    # First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    customer = OneToOneField(
        Customer,
        null=True, blank=True,
        on_delete=CASCADE,
        related_name='user',
        unique=True
    )

    def get_absolute_url(self) -> str:
        """Get URL for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

infoparlamento/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        error_messages = {
            "username": {"unique": _("This username has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

infoparlamento/newsletter/views.py
from datetime import datetime
from typing import Any

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.postgres.search import SearchQuery, SearchRank, SearchHeadline
from django.core.exceptions import PermissionDenied
from django.db.models import FilteredRelation, Q, Count, F
from django.http import JsonResponse, HttpResponse
from django.template.loader import get_template
from django.views.generic import DetailView, ListView

from django.conf import settings
from weasyprint import HTML
from weasyprint.text.fonts import FontConfiguration

from infoparlamento.newsletter.models import News, Newsletter, Tag, Category


class NewsDetailView(LoginRequiredMixin, DetailView):
    model = News

    def get(self, request, *args, **kwargs):
        if (
            not self.request.user.is_superuser and
            not self.request.user.groups.filter(name='Redattori') and
            not self.request.user.groups.filter(name='Amministratori') and
            not self.get_object().customernews_set.filter(
                customer=self.request.user.customer,
                is_excluded=False
            )
        ):
            raise PermissionDenied

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['url_prefix'] = settings.EMAIL_URL_PREFIX
        context['news_tags'] = ", ".join([t.denominazione for t in self.get_object().tags])
        return context


news_detail_view = NewsDetailView.as_view()


class NewsPdfView(LoginRequiredMixin, DetailView):
    model = News
    template_name = 'newsletter/news_detail_pdf.html'

    def get(self, request, *args, **kwargs):
        if (
            not self.request.user.is_superuser and
            not self.request.user.groups.filter(name='Redattori') and
            not self.request.user.groups.filter(name='Amministratori') and
            not self.get_object().customernews_set.filter(
                customer=self.request.user.customer,
                is_excluded=False
            )
        ):
            raise PermissionDenied

        # Get the template
        template = get_template(self.template_name)

        # Get the object
        self.object = self.get_object()

        # Get context
        context = self.get_context_data()

        # Render template
        html_string = template.render(context)

        # Generate PDF
        font_config = FontConfiguration()
        html = HTML(string=html_string, base_url=request.build_absolute_uri('/'))
        pdf = html.write_pdf(font_config=font_config)

        # Create response
        response = HttpResponse(pdf, content_type='application/pdf')
        response['Content-Disposition'] = f'filename=news_{self.object.id}.pdf'
        return response

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['url_prefix'] = settings.EMAIL_URL_PREFIX
        context['news_tags'] = self.object.tags_names
        return context


news_pdf_view = NewsPdfView.as_view()

class NewsletterListView(LoginRequiredMixin, ListView):
    model = Newsletter
    paginate_by = settings.NEWSLETTERS_LIST_PAGE_SIZE

    def get_queryset(self):
        filter_year = int(self.request.GET.get('anno', datetime.now().year))
        queryset = self.model.objects.filter(
            Q(sent_at__year=filter_year) | Q(sent_at__isnull=True)
        )
        if (
            not self.request.user.is_superuser and
            not self.request.user.groups.filter(name='Redattori') and
            not self.request.user.groups.filter(name='Amministratori')
        ):
            queryset = queryset.filter(
                sent_at__isnull=False,
                news__customernews__customer=self.request.user.customer
            )
        return queryset.annotate(n_news=Count('news')).order_by('-sent_at')

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['filter_years'] = list(
            self.model.objects.order_by('-sent_at__year').values_list('sent_at__year', flat=True).distinct()
        )
        context['filter_selected_year'] = int(self.request.GET.get('anno', datetime.now().year))
        return context


newsletter_list_view = NewsletterListView.as_view()


class NewsletterDetailView(LoginRequiredMixin, DetailView):
    model = Newsletter

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)

        newsletter = self.get_object()
        news = newsletter.news.all()
        if (
            not self.request.user.is_superuser and
            not self.request.user.groups.filter(name='Redattori') and
            not self.request.user.groups.filter(name='Amministratori')
        ):
            news = news.filter(
                customernews__customer=self.request.user.customer,
                customernews__is_excluded=False
            )

        context['newsletter'] = newsletter
        context['newsletter_news'] = news.annotate(
            n=FilteredRelation(
                "category__newslettercategory",
                condition=Q(category__newslettercategory__newsletter=newsletter)
            )
        ).order_by('n__priority', 'n', 'number')
        return context


newsletter_detail_view = NewsletterDetailView.as_view()


class NewsSearchView(ListView):
    model = News
    template_name = "newsletter/news_search.html"

    # def get_queryset(self):
    #
    #     order_by = self.request.GET.get('order_by', 'date')
    #     query_string = self.request.GET.get('q', '')
    #     tag_filter = self.request.GET.getlist('tag')
    #     search_query = SearchQuery(query_string, search_type='websearch')
    #
    #     # annotate news with full-text search arguments
    #     results = self.model.objects.annotate(
    #         search_rank=SearchRank(F('search_vector'), search_query),
    #         headline_title=SearchHeadline(
    #             'title', search_query,
    #             start_sel='<span class="headline">', stop_sel='</span>',
    #             highlight_all=True
    #         ),
    #         headline_text=SearchHeadline(
    #             'text', search_query,
    #             start_sel='<span class="headline">',
    #             stop_sel='</span>'
    #         )
    #     ).filter(
    #         is_ready=True,
    #         search_vector=search_query
    #     )
    #
    #     if tag_filter:
    #         results = results.filter(tags_rels__tag__denominazione__in=tag_filter)
    #
    #     # filter news according to users' visibility over them
    #     if (
    #         not self.request.user.is_superuser and
    #         not self.request.user.groups.filter(name='Redattori') and
    #         not self.request.user.groups.filter(name='Amministratori')
    #     ):
    #         results = results.filter(
    #             sent_at__isnull=False,
    #             customernews__customer=self.request.user.customer,
    #             customernews__is_excluded=False
    #         )
    #
    #     # based on order_by parameters, sort news
    #     if order_by == 'date':
    #         results = results.order_by("-date", "-search_rank")
    #     else:
    #         results = results.order_by("-search_rank", "-date")
    #     return results[:settings.NEWSLETTERS_SEARCH_RESULTS_PER_PAGE]

    def get_base_queryset(self):
        """Get the base queryset for computing facets, before pagination but after permissions"""
        query_string = self.request.GET.get('q', '')
        search_query = SearchQuery(query_string, search_type='websearch')

        # Start with all ready news that match the search
        base_qs = self.model.objects.annotate(
            search_rank=SearchRank(F('search_vector'), search_query),
            headline_title=SearchHeadline(
                'title', search_query,
                start_sel='<span class="headline">', stop_sel='</span>',
                highlight_all=True
            ),
            headline_text=SearchHeadline(
                'text', search_query,
                start_sel='<span class="headline">',
                stop_sel='</span>'
            )
        ).filter(
            is_ready=True,
            search_vector=search_query
        )

        # Apply permission filtering
        if not (self.request.user.is_superuser or
                self.request.user.groups.filter(name__in=['Redattori', 'Amministratori'])):
            base_qs = base_qs.filter(
                sent_at__isnull=False,
                customernews__customer=self.request.user.customer,
                customernews__is_excluded=False
            )

        return base_qs

    def get_queryset(self):
        base_qs = self.get_base_queryset()

        # Apply category filter if selected
        selected_categories = self.request.GET.getlist('category')
        if selected_categories:
            base_qs = base_qs.filter(category__name__in=selected_categories)

        self.total_filtered_count = base_qs.count()

        # Apply ordering
        order_by = self.request.GET.get('order_by', 'date')
        if order_by == 'date':
            base_qs = base_qs.order_by("-date", "-search_rank")
        else:
            base_qs = base_qs.order_by("-search_rank", "-date")

        return base_qs[:settings.NEWSLETTERS_SEARCH_RESULTS_PER_PAGE]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query_string = self.request.GET.get('q', '')
        selected_categories = self.request.GET.getlist('category')

        # Get base queryset for faceting
        base_qs = self.get_base_queryset()

        # Store the total count without category filters
        total_unfiltered_count = base_qs.count()

        # Get categories and their counts
        category_counts = Category.objects.filter(

infoparlamento/users/views.py
import logging
from functools import wraps

from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import redirect, get_object_or_404
from django.contrib import messages



User = get_user_model()
logger = logging.getLogger(__name__)

class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert self.request.user.is_authenticated  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

@staff_member_required
def impersonate_user(request, user_id):
    user_to_impersonate = get_object_or_404(User, id=user_id)

    request.session['impersonate_id'] = user_to_impersonate.id
    return redirect('newsletter:newsletter_list')


def stop_impersonation(request):
    request.session.pop('impersonate_id', None)
    messages.success(request, "Fine anteprima")
    return redirect('admin:newsletter_customer_changelist')

infoparlamento/templates/base.html
{% load static i18n %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
<head>

  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Sistema di invio newsletter InfoParlamento">
  <meta name="author" content="Guglielmo Celata per Depp SRL">
  <meta charset="UTF-8">


  <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicons/apple-touch-icon.png'%}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicons/favicon-32x32.png'%}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicons/favicon-16x16.png'%}">
  <link rel="manifest" href="{% static 'images/favicons/site.webmanifest'%}">
  <link rel="mask-icon" href="{% static 'images/favicons/safari-pinned-tab.svg'%}" color="#5bbad5">
  <meta name="msapplication-TileColor" content="#da532c">
  <meta name="theme-color" content="#ffffff">

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
  <link
    href="https://fonts.googleapis.com/css2?family=Titillium+Web:ital,wght@0,400;0,600;0,700;1,400;1,600&amp;display=swap"
    rel="stylesheet">
  <title>{% block title %}Informazioni Parlamentari{% endblock title %}</title>


  {% block css %}
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/css/bootstrap.min.css"
          integrity="sha512-GQGU0fMMi238uA+a/bdWJfpUGKUkBdgfFdgBm72SUQ6BeyWjoY/ton0tEjH+OSH9iP4Dfh+7HM0I9f5eR0L/4w=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>

    <!-- Your stuff: Third-party CSS libraries go here -->
    <!-- fontawesome-free v6.4.0 -->
    <link rel="stylesheet" href="{% static 'fonts/fontawesome-free-6.4.0-web/css/all.min.css' %}">

    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">

  {% endblock %}

  <!-- Le javascript
  ================================================== -->
  {# Placed at the top of the document so pages load faster with defer #}
  {% block javascript %}

    <!-- Your stuff: Third-party javascript libraries go here -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- ✅ load popper.js ✅ -->
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
      integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
      crossorigin="anonymous"
    ></script>

    <!-- Bootstrap JS -->
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.min.js"
            integrity="sha512-OvBgP9A2JBgiRad/mM36mkzXSXaJE9BEIENnVEmeZdITvwT09xnxLtT4twkCa8m/loMbPHsvPl0T8lRGVBwjlQ=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <!-- place project specific Javascript in this file -->
    <script defer src="{% static 'js/project.js' %}"></script>

  {% endblock javascript %}

</head>

<body>

<div class="container">
  {% if request.user.is_authenticated %}
    <nav class="navbar navbar-expand-lg navbar-light">
      <div class="container-fluid d-flex align-items-end py-2">
        <a class="navbar-brand" href="{% url 'home' %}">
          <img src="{% static 'images/info_parlamento.png' %}" alt="Logo InfoParlamento">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse mt-4 mt-lg-0" id="navbarNav">
          <ul class="navbar-nav ">
            <li class="nav-item">
              {% if request.real_user %}
                {{ request.user.name }}
                <a href="{% url 'users:stop-impersonation' %}" title="Torna all'elenco utenti">Fine anteprima</a>
            {% else %}
              Ciao {{ request.user.name }},
            {% endif %}
            {% if not request.real_user %}
                <a
                   href="{% url 'account_logout' %}">{% translate "Sign Out"|lower %}</a>
            {% endif %}
            </li>
            <li class="nav-item">
              <a href="{% url 'newsletter:newsletter_list' %}">Archivio monitoraggio</a>
            </li>
            <li class="nav-item">
              <form action="{% url 'newsletter:news_search' %}" method="get"><input name="q" type="text" placeholder="Cerca..."></form>
            </li>
          </ul>
        </div>
      </div>
    </nav>

  {% endif %}
</div> <!-- /container -->

{% block content %}
  <p>Use this document as a way to quick start any new project.</p>
{% endblock content %}

<div id="footer" class="container mt-5 mt-lg-0">

  <footer class="mt-5">
    <div class="row d-flex align-items-end">
      <div class="col-auto">
        <img src="{% static 'images/info_parlamento.png' %}" alt="Logo InfoParlamento" width="140" height="89">
      </div>
      <div class="col-auto"> © Copyright 2017 SEBA S.a.s. - P.IVA 07511321007</div>
      <div class="col-auto ms-lg-auto mt-3 mt-lg-0"><a class="footer-link" href="{% url 'privacy' %}">Privacy Policy</a></div>
{#      <div class="col-auto"><a class="footer-link" href="{% url 'cookie' %}">Cookie Policy</a></div>#}
    </div>
  </footer>

</div>

{% block modal %}{% endblock modal %}

{% block inline_javascript %}
  {% comment %}
    Script tags with only code, no src (defer by default). To run
    with a "defer" so that you run inline code:
    <script>
      window.addEventListener('DOMContentLoaded', () => {/* Run whatever you want */});
    </script>
    {% endcomment %}
{% endblock inline_javascript %}
</body>
</html>

infoparlamento/templates/base_email.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml"
      xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="x-apple-disable-message-reformatting">
  <title>Newsletter Infoparlamento</title>
  <style>

    html,
    body {
      margin: 0 auto !important;
      padding: 0 !important;
      height: 100% !important;
      width: 100% !important;
      background: #f1f1f1;
    }


    * {
      -ms-text-size-adjust: 100%;
      -webkit-text-size-adjust: 100%;
    }


    div[style*="margin: 16px 0"] {
      margin: 0 !important;
    }


    td {
      mso-table-lspace: 0pt !important;
      mso-table-rspace: 0pt !important;
    }


    img {
      -ms-interpolation-mode: bicubic;
    }


    a {
      text-decoration: none;
    }

    .tag {
      background-color: #BB7300;
      display: inline-block;
      border-radius: 6px;
      color: #fff;
      padding: 4px 8px;
      font-size: 13px;
      text-transform: uppercase;
    }


    @media only screen and (min-device-width: 320px) and (max-device-width: 374px) {
      u ~ div .email-container {
        min-width: 320px !important;
      }
    }

    @media only screen and (min-device-width: 375px) and (max-device-width: 413px) {
      u ~ div .email-container {
        min-width: 375px !important;
      }
    }

    @media only screen and (min-device-width: 414px) {
      u ~ div .email-container {
        min-width: 414px !important;
      }
    }

    .bg_white {
      background: #ffffff;
    }


    body {
      font-family: 'Work Sans', sans-serif;
      font-weight: 400;
      font-size: 15px;
      line-height: 1.8;
      color: rgba(0, 0, 0, .4);
    }

    a {
      color: #2072D9
    }


    .container {
      padding: 0 2em;
      color: #000;
    }

    .news {
      padding-bottom: 0.5em;
      color: #000;
      font-size: 18px;
      line-height: 1.3;
    }

    .tag {
      padding: 3px 4px 2px 4px;
      font-size: 12px;
    }

  </style>


</head>

<body width="100%" style="margin: 0; padding: 0 !important; mso-line-height-rule: exactly; background-color: #f1f1f1;">
<center style="width: 100%; background-color: #f1f1f1;">
  <div
    style="display: none; font-size: 1px;max-height: 0px; max-width: 0px; opacity: 0; overflow: hidden; mso-hide: all; font-family: sans-serif;">
    &zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;
  </div>

  <table border="0" cellspacing="0" width="100%">
      <tr>
          <td></td>
          <td width="100%">
            <table class="bg_white" align="center" cellspacing="0" cellpadding="0" border="0" width="100%"
                   style="margin: auto; padding: 1em 2.5em 0 2.5em; text-align: center;">
              <tr>
                <td height="89" style="">
                  <img src="{{ img_url_prefix }}{% static 'images/info_parlamento.png' %}" width="140" height="89" border="0" alt="Logo" />
                </td>
              </tr>
            </table>

            {% block content %}{% endblock %}

            <table class="bg_white" align="center" cellspacing="0" cellpadding="0" border="0" width="100%"
                   style="margin: auto; padding: 1em 2.5em 0 2.5em; text-align: center;">
              <tr>
              <tr>
                <td height="89" style="">
                  <img src="{{ img_url_prefix }}{% static 'images/info_parlamento.png' %}" width="140" height="89" border="0" alt="" / >
                </td>
              </tr>
              <tr>
                <td style="vertical-align:bottom; font-size: 15px; padding-bottom: 2em;">
                  © Copyright 2017 SEBA S.a.s. - P.IVA 07511321007
                </td>
              </tr>
            </table>
          </td>
          <td></td>
       </tr>
  </table>

</center>
</body>
</html>

infoparlamento/templates/cookie.html
{% extends "base.html" %}
{% load static i18n %}
{% load markdown_tags %}

{% block title %} Cookie policy - Informazioni Parlamentari{% endblock title %}

{% block content %}
  <div id="header" class="container-fluid hero">
    <div class="container">

      <div class="d-flex justify-content-center title-page">
        Cookie policy
      </div>
    </div>
  </div>

  <div id="curve" class="curve">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 70">
      <path fill="#2072D9" fill-opacity="1" d="M0,58,120,47.3C240,37,480,15,720,10s480,5,600,10.7L1440,26V0H0Z"></path>
    </svg>
  </div>

  <div class="container mt-4 bb-1 pb-4">

  {% markdown %}

  # La nostra cookie policy

  Questa pagina contiene la nostra privacy policy e può essere scritta in Markdown.

  {% endmarkdown %}

  </div>
{% endblock %}