config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView, RedirectView

urlpatterns = [
                  path("", RedirectView.as_view(url="/newsletters"), name="home"),
                  # Django Admin, use {% url 'admin:index' %}
                  path(settings.ADMIN_URL, admin.site.urls),
                  # User management
                  path("users/", include("infoparlamento.users.urls", namespace="users")),
                  path("accounts/", include("allauth.urls")),
                  # Your stuff: custom urls includes go here
                  path("newsletters/", include("infoparlamento.newsletter.urls", namespace="newsletter")),
                  path("privacy/", TemplateView.as_view(template_name="privacy.html"), name="privacy"),
                  path("cookie/", TemplateView.as_view(template_name="cookie.html"), name="cookie"),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('django-rq/', include('django_rq.urls'))
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

infoparlamento/newsletter/urls.py
from django.urls import path

from infoparlamento.newsletter import views
from infoparlamento.newsletter.views import (
    news_detail_view, news_search_view, newsletter_detail_view, news_pdf_view, newsletter_list_view
)

app_name = "newsletter"
urlpatterns = [
    path("", view=newsletter_list_view, name="newsletter_list"),
    path("<int:pk>/", view=newsletter_detail_view, name="newsletter_detail"),
    path("news/<int:pk>/", view=news_detail_view, name="news_detail"),
    path('news/<int:pk>/pdf/', view=news_pdf_view, name='news_pdf'),
    path("ricerca/", view=news_search_view, name="news_search"),
    path('admin/get_subtags/', views.get_subtags, name='get_subtags'),
]

infoparlamento/users/urls.py
from django.urls import path

from infoparlamento.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view, impersonate_user, stop_impersonation,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path('impersonate/<int:user_id>/', view=impersonate_user, name='impersonate-user'),
    path('stopimpersonation/', view=stop_impersonation, name='stop-impersonation'),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

infoparlamento/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField, ForeignKey, CASCADE, OneToOneField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from infoparlamento.newsletter.models import Customer


class User(AbstractUser):
    """
    Default custom user model for InfoParlamento.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    # First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    customer = OneToOneField(
        Customer,
        null=True, blank=True,
        on_delete=CASCADE,
        related_name='user',
        unique=True
    )

    def get_absolute_url(self) -> str:
        """Get URL for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

infoparlamento/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        error_messages = {
            "username": {"unique": _("This username has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

infoparlamento/newsletter/views.py
from datetime import datetime
from typing import Any

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.postgres.search import SearchQuery, SearchRank, SearchHeadline
from django.core.exceptions import PermissionDenied
from django.db.models import FilteredRelation, Q, Count, F
from django.http import JsonResponse, HttpResponse
from django.template.loader import get_template
from django.views.generic import DetailView, ListView

from django.conf import settings
from weasyprint import HTML
from weasyprint.text.fonts import FontConfiguration

from infoparlamento.newsletter.models import News, Newsletter, Tag, Category


class NewsDetailView(LoginRequiredMixin, DetailView):
    model = News

    def get(self, request, *args, **kwargs):
        if (
            not self.request.user.is_superuser and
            not self.request.user.groups.filter(name='Redattori') and
            not self.request.user.groups.filter(name='Amministratori') and
            not self.get_object().customernews_set.filter(
                customer=self.request.user.customer,
                is_excluded=False
            )
        ):
            raise PermissionDenied

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['url_prefix'] = settings.EMAIL_URL_PREFIX
        context['news_tags'] = ", ".join([t.denominazione for t in self.get_object().tags])
        return context


news_detail_view = NewsDetailView.as_view()


class NewsPdfView(LoginRequiredMixin, DetailView):
    model = News
    template_name = 'newsletter/news_detail_pdf.html'

    def get(self, request, *args, **kwargs):
        if (
            not self.request.user.is_superuser and
            not self.request.user.groups.filter(name='Redattori') and
            not self.request.user.groups.filter(name='Amministratori') and
            not self.get_object().customernews_set.filter(
                customer=self.request.user.customer,
                is_excluded=False
            )
        ):
            raise PermissionDenied

        # Get the template
        template = get_template(self.template_name)

        # Get the object
        self.object = self.get_object()

        # Get context
        context = self.get_context_data()

        # Render template
        html_string = template.render(context)

        # Generate PDF
        font_config = FontConfiguration()
        html = HTML(string=html_string, base_url=request.build_absolute_uri('/'))
        pdf = html.write_pdf(font_config=font_config)

        # Create response
        response = HttpResponse(pdf, content_type='application/pdf')
        response['Content-Disposition'] = f'filename=news_{self.object.id}.pdf'
        return response

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['url_prefix'] = settings.EMAIL_URL_PREFIX
        context['news_tags'] = self.object.tags_names
        return context


news_pdf_view = NewsPdfView.as_view()

class NewsletterListView(LoginRequiredMixin, ListView):
    model = Newsletter
    paginate_by = settings.NEWSLETTERS_LIST_PAGE_SIZE

    def get_queryset(self):
        filter_year = int(self.request.GET.get('anno', datetime.now().year))
        queryset = self.model.objects.filter(
            Q(sent_at__year=filter_year) | Q(sent_at__isnull=True)
        )
        if (
            not self.request.user.is_superuser and
            not self.request.user.groups.filter(name='Redattori') and
            not self.request.user.groups.filter(name='Amministratori')
        ):
            queryset = queryset.filter(
                sent_at__isnull=False,
                news__customernews__customer=self.request.user.customer
            )
        return queryset.annotate(n_news=Count('news')).order_by('-sent_at')

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['filter_years'] = list(
            self.model.objects.order_by('-sent_at__year').values_list('sent_at__year', flat=True).distinct()
        )
        context['filter_selected_year'] = int(self.request.GET.get('anno', datetime.now().year))
        return context


newsletter_list_view = NewsletterListView.as_view()


class NewsletterDetailView(LoginRequiredMixin, DetailView):
    model = Newsletter

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)

        newsletter = self.get_object()
        news = newsletter.news.all()
        if (
            not self.request.user.is_superuser and
            not self.request.user.groups.filter(name='Redattori') and
            not self.request.user.groups.filter(name='Amministratori')
        ):
            news = news.filter(
                customernews__customer=self.request.user.customer,
                customernews__is_excluded=False
            )

        context['newsletter'] = newsletter
        context['newsletter_news'] = news.annotate(
            n=FilteredRelation(
                "category__newslettercategory",
                condition=Q(category__newslettercategory__newsletter=newsletter)
            )
        ).order_by('n__priority', 'n', 'number')
        return context


newsletter_detail_view = NewsletterDetailView.as_view()


class NewsSearchView(ListView):
    model = News
    template_name = "newsletter/news_search.html"

    # def get_queryset(self):
    #
    #     order_by = self.request.GET.get('order_by', 'date')
    #     query_string = self.request.GET.get('q', '')
    #     tag_filter = self.request.GET.getlist('tag')
    #     search_query = SearchQuery(query_string, search_type='websearch')
    #
    #     # annotate news with full-text search arguments
    #     results = self.model.objects.annotate(
    #         search_rank=SearchRank(F('search_vector'), search_query),
    #         headline_title=SearchHeadline(
    #             'title', search_query,
    #             start_sel='<span class="headline">', stop_sel='</span>',
    #             highlight_all=True
    #         ),
    #         headline_text=SearchHeadline(
    #             'text', search_query,
    #             start_sel='<span class="headline">',
    #             stop_sel='</span>'
    #         )
    #     ).filter(
    #         is_ready=True,
    #         search_vector=search_query
    #     )
    #
    #     if tag_filter:
    #         results = results.filter(tags_rels__tag__denominazione__in=tag_filter)
    #
    #     # filter news according to users' visibility over them
    #     if (
    #         not self.request.user.is_superuser and
    #         not self.request.user.groups.filter(name='Redattori') and
    #         not self.request.user.groups.filter(name='Amministratori')
    #     ):
    #         results = results.filter(
    #             sent_at__isnull=False,
    #             customernews__customer=self.request.user.customer,
    #             customernews__is_excluded=False
    #         )
    #
    #     # based on order_by parameters, sort news
    #     if order_by == 'date':
    #         results = results.order_by("-date", "-search_rank")
    #     else:
    #         results = results.order_by("-search_rank", "-date")
    #     return results[:settings.NEWSLETTERS_SEARCH_RESULTS_PER_PAGE]

    def get_base_queryset(self):
        """Get the base queryset for computing facets, before pagination but after permissions"""
        query_string = self.request.GET.get('q', '')
        search_query = SearchQuery(query_string, search_type='websearch')

        # Start with all ready news that match the search
        base_qs = self.model.objects.annotate(
            search_rank=SearchRank(F('search_vector'), search_query),
            headline_title=SearchHeadline(
                'title', search_query,
                start_sel='<span class="headline">', stop_sel='</span>',
                highlight_all=True
            ),
            headline_text=SearchHeadline(
                'text', search_query,
                start_sel='<span class="headline">',
                stop_sel='</span>'
            )
        ).filter(
            is_ready=True,
            search_vector=search_query
        )

        # Apply permission filtering
        if not (self.request.user.is_superuser or
                self.request.user.groups.filter(name__in=['Redattori', 'Amministratori'])):
            base_qs = base_qs.filter(
                sent_at__isnull=False,
                customernews__customer=self.request.user.customer,
                customernews__is_excluded=False
            )

        return base_qs

    def get_queryset(self):
        base_qs = self.get_base_queryset()

        # Apply category filter if selected
        selected_categories = self.request.GET.getlist('category')
        if selected_categories:
            base_qs = base_qs.filter(category__name__in=selected_categories)

        self.total_filtered_count = base_qs.count()

        # Apply ordering
        order_by = self.request.GET.get('order_by', 'date')
        if order_by == 'date':
            base_qs = base_qs.order_by("-date", "-search_rank")
        else:
            base_qs = base_qs.order_by("-search_rank", "-date")

        return base_qs[:settings.NEWSLETTERS_SEARCH_RESULTS_PER_PAGE]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query_string = self.request.GET.get('q', '')
        selected_categories = self.request.GET.getlist('category')

        # Get base queryset for faceting
        base_qs = self.get_base_queryset()

        # Store the total count without category filters
        total_unfiltered_count = base_qs.count()

        # Get categories and their counts
        category_counts = Category.objects.filter(

infoparlamento/users/views.py
import logging
from functools import wraps

from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import redirect, get_object_or_404
from django.contrib import messages



User = get_user_model()
logger = logging.getLogger(__name__)

class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert self.request.user.is_authenticated  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

@staff_member_required
def impersonate_user(request, user_id):
    user_to_impersonate = get_object_or_404(User, id=user_id)

    request.session['impersonate_id'] = user_to_impersonate.id
    return redirect('newsletter:newsletter_list')


def stop_impersonation(request):
    request.session.pop('impersonate_id', None)
    messages.success(request, "Fine anteprima")
    return redirect('admin:newsletter_customer_changelist')

infoparlamento/templates/newsletter/email_single_news_template.html
{% extends "base_email.html" %}
{% load static %}

{% block content %}

    <table class="bg_white" border="0" cellpadding="0" cellspacing="0" width="100%">
      <tr>
        <td bgcolor="#2072D9"
            style="text-align: center; font-size: 18px;  color: #fff; padding: 40px 20px 10px 20px; border-top: 3px solid #BB7300;"
            border="0">
          {{ news.sent_at|date:"d/m/Y" }}
        </td>
      </tr>
      <tr>
        <td bgcolor="#2072D9"
            style="text-align: center; font-size: 25px; line-height: 1.3;  color: #fff; padding: 0px 20px 40px 20px;"
            border="0">
          {{ news.title }}
        </td>
      </tr>
      <tr>
        <td width="100%" height="48" style="padding:0;" border="0" style="padding: 40px 20px 20px 20px;">
          <img src="{{ img_url_prefix }}{% static 'images/curva.png' %}" width="100%" height="48" border="0" alt="" / >
        </td>
      </tr>
    </table>

      <table class="bg_white container news" border="0" cellpadding="0" cellspacing="0" width="100%">
        <tr>
          <td border="0" style="">
            <img src="{{ img_url_prefix }}{% static 'images/arrow.png' %}" style="padding:0px 5px 0px 0px;" width="9" height="13" border="0" alt="Arrow" /><a
            href="{{ url_prefix }}{% url 'newsletter:news_detail' news.id %}"><strong>{{ news.title }}</strong></a>
          </td>
        </tr>

        <tr>
{#          {% for tag in news.tags %}#}
{#            <td border="0" class="tag" style="margin-right: 1em;">#}
{#              {{ tag.denominazione }}#}
{#            </td>#}
{#          {% endfor %}#}
          <td border="0" style="margin-right: 1em; display: inline-block;">
          {% if news.files.count %}
            <img src="{{ img_url_prefix }}{% static 'images/paperclip.png' %}" style="padding:0px 2px 0px 0px;" width="19" height="22" border="0" alt="Paperclip" />
            {{ news.files.count }}
            {% if news.files.count > 1 %}
              allegati
            {% else %}
              allegato
            {% endif %}
          {% endif %}
        </tr>

        <tr>
          <td border="0" style="">
            {{ news.text|safe }}
          </td>
        </tr>

      </table>

{% endblock %}

infoparlamento/templates/newsletter/email_template.html
{% extends "base_email.html" %}
{% load static %}

{% block content %}

    <table class="bg_white" border="0" cellpadding="0" cellspacing="0" width="100%">
      <tr>
        <td bgcolor="#2072D9"
            style="text-align: center; font-size: 18px;  color: #fff; padding: 40px 20px 10px 20px; border-top: 3px solid #BB7300;"
            border="0">
          {{ newsletter.sent_at|date:"d/m/Y" }}
        </td>
      </tr>
      <tr>
        <td bgcolor="#2072D9"
            style="text-align: center; font-size: 25px; line-height: 1.3;  color: #fff; padding: 0px 20px 40px 20px;"
            border="0">
          {{ newsletter.title }}
        </td>
      </tr>
      <tr>
        <td width="100%" height="48" style="padding:0;" border="0" style="padding: 40px 20px 20px 20px;">
          <img src="{{ img_url_prefix }}{% static 'images/curva.png' %}" width="100%" height="48" border="0" alt="" / >
        </td>
      </tr>
    </table>

    {% if newsletter.introductory_text %}
    <table class="bg_white container" width="100%" text-align="center" cellpadding="0" cellspacing="0" border="0">
      <tr>
        <td width="35" height="25" style="padding:0.3em 0 0 0; vertical-align:top" border="0">
          <img src="{{ img_url_prefix }}{% static 'images/book.png' %}" width="35" height="25" border="0" alt="booklet" / >
        </td>
        <td border="0" style="padding:0 2.5em 0 1em ; font-size: 17px; line-height: 1.3; color: #000">
           {{ newsletter.introductory_text }}
        </td>
      </tr>
    </table>
    {% endif %}

  {% regroup news by category as news_by_category %}
  {% for newsgroup in news_by_category %}
    <table class="bg_white container" border="0" cellpadding="0" cellspacing="0" width="100%">
      <tr>
        <td border="0" style="padding:2em 0 1em 0; font-size: 18px; color: #000; border-bottom: 1px solid #D9D9D9;">
        <strong>{{ newsgroup.grouper }}</strong>
        </td>
      </tr>
    </table>


    {% for news in newsgroup.list %}

      <table class="bg_white container news" border="0" cellpadding="0" cellspacing="0" width="100%">
        <tr>
          <td border="0" style="">
            <img src="{{ img_url_prefix }}{% static 'images/arrow.png' %}" style="padding:0px 5px 0px 0px;" width="9" height="13" border="0" alt="Arrow" /><a
            href="{{ url_prefix }}{% url 'newsletter:news_detail' news.id %}"><strong>{{ news.title }}</strong></a>
          </td>
        </tr>

        <tr>
          <td border="0" style="margin-right: 1em; display: inline-block;">
          {% if news.files.count %}
            <img src="{{ img_url_prefix }}{% static 'images/paperclip.png' %}" style="padding:0px 2px 0px 0px;" width="19" height="22" border="0" alt="Paperclip" />
            {{ news.files.count }}
            {% if news.files.count > 1 %}
              allegati
            {% else %}
              allegato
            {% endif %}
          {% endif %}
        </tr>
      </table>

    {% endfor %}
  {% endfor %}
{% endblock %}

infoparlamento/templates/newsletter/news_change_form.html
{% extends 'admin/change_form.html' %}
{% load users_extras %}

{% block submit_buttons_top %}
  {{ block.super }}
  {% if original.sent_at is None %}
    {% if request.user|has_group:"Amministratori" or request.user.is_superuser %}
      <div class="submit-row" style="display: flex; justify-content: flex-end;">
        <input type="submit" value="Invia a tutti" name="_send-all"
               title="Invia questa notizia a tutti gli utenti"
               style="background-color: darkorange!important;">
      </div>
    {% endif %}
  {% endif %}
{% endblock %}

infoparlamento/templates/newsletter/news_detail.html
{% extends 'base.html' %}

{% block content %}
  <div>
    <div class="container-fluid hero">
      <div class="container">
        {% if news.newsletter %}
          <div class="mt-3 briciole">
            <a href="{% url 'newsletter:newsletter_list' %}">Archivio monitoraggio</a> /
              <a href="{% url 'newsletter:newsletter_detail' news.newsletter.id %}">{{ news.newsletter.title }}</a> /
            {{ news.title|truncatewords_html:7 }}
          </div>
        {% endif %}
        <div class="title-news-page">
          <div class="row d-flex justify-content-start">
            <div class="data-anno mb-3">{{ news.date|date:"d M Y" }}</div>
            <div class="title">{{ news.title }}</div>
            <div class="download-pdf">
              <a href="{% url 'newsletter:news_pdf' news.id %}" class="pdf-button">
                  <i class="fa fa-file-pdf"></i>
                  Scarica PDF
              </a>
            </div>

          </div>
        </div>
      </div>
    </div>
    <div class="curve">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 70">
        <path fill="#2072D9" fill-opacity="1"
              d="M0,58,120,47.3C240,37,480,15,720,10s480,5,600,10.7L1440,26V0H0Z"></path>
      </svg>
    </div>
    <div class="container mt-5 mt-lg-0">
      <div class="container mt-4 pb-4 bb-1 mb-4">
        <div class="pb-2 mb-2 fw-700">{{ news.category }}</div>
        {% if news.files.count == 1 %}
          <div class="mb-1">Allegato:</div>
        {% elif news.files.count > 1 %}
          <div class="mb-1">Allegato:</div>
        {% else %}
        {% endif %}
        {% for attach in news.files.all %}
          <div>
            <i class="fa-solid fa-paperclip blue me-1 mb-2"></i>
            <a class="blue"
               href="{{ attach.file.url }}">{{ attach.name|default_if_none:attach.filename }}</a>
          </div>
        {% endfor %}
      </div>

      <div class="row justify-content-between d-flex align-items-start mb-4">
        <div class="col">
          <div class="mx-2">{{ news.text|safe }}</div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

infoparlamento/templates/newsletter/news_search.html
{% extends 'base.html' %}

{% block content %}

  <div class="container-fluid hero">
    <div class="container">
      <div class="mt-3 briciole"><a href="{% url 'newsletter:newsletter_list' %}">Archivio monitoraggio</a>
        / Ricerca</div>
      <div class="title-newsletter-page">
        <div class="row d-flex justify-content-center text-center">
            <div class="">{{ total_count }} risultati della ricerca per <i>{{ query }}</i></div>
        </div>
      </div>
    </div>
  </div>

  <div class="curve">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 70">
      <path fill="#2072D9" fill-opacity="1" d="M0,58,120,47.3C240,37,480,15,720,10s480,5,600,10.7L1440,26V0H0Z"></path>
    </svg>
  </div>

  <div class="container mt-5 mt-lg-0">

    <div class="container mt-4 pb-4">
      <div class="content">

        <div class="row">
          <div class="col-md-3">
            <h4>Filtra per tipo di atto parlamentare</h4>
            <form method="get" action="">
                <input type="hidden" name="q" value="{{ query }}">
                <input type="hidden" name="order_by" value="{{ order_by }}">
                {% for category in category_facets %}
                <div class="form-check">
                    <input type="checkbox"
                           name="category"
                           value="{{ category.name }}"
                           {% if category.name in selected_categories %}checked{% endif %}
                           class="form-check-input"
                           id="category-{{ forloop.counter }}">
                    <label class="form-check-label" for="category-{{ forloop.counter }}">
                        {{ category.name|slice:"12:" }} ({{ category.count }})
                    </label>
                </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary mt-3">Applica filtro</button>
            </form>
          </div>
          <div class="col-md-9">
            <div class="row mt-1 mb-5">
              <div class="col">
                Ordinamento per:
                {% if order_by == 'date' %}data{% else %}<a href="./?q={{ query|urlencode }}&order_by=date">data</a>{% endif %}
                |
                {% if order_by == 'search_rank' %}rilevanza{% else %}<a href="./?q={{ query|urlencode }}&order_by=search_rank">rilevanza</a>{% endif %}
              </div>
            </div>
            {% for news in news_list %}
              <div class="row justify-content-between d-flex align-items-start mb-4 ms-2">
                <div class="col-auto text-center p-0">
                  <i class="fa-solid fa-angle-right blue"></i>
                </div>
                <div class="col">
                  <div>{{ news.date }}</div>
                  {% if news.newsletter %}
                    <div>
                      {% if news.newsletter.sent_at %}
                        Inviata con la newsletter
                        <i>{{ news.newsletter.title }}</i> del {{ news.newsletter.sent_at }}
                      {% else %}
                        Assegnata alla newsletter
                        <i>{{ news.newsletter.title }}</i>, ancora in fase di lavorazione
                      {% endif %}
                    </div>
                  {% endif %}
                  <div class="news-title mb-1">
                    <a
                      href="{{ url_prefix }}{% url 'newsletter:news_detail' news.id %}">{{ news.headline_title|safe }}</a>
                  </div>
                  <div class="news-text mb-1">
                    {% if query in news.headline_text %}
                      ... {{ news.headline_text|safe }} ...
                    {% endif %}
                  </div>
                  <div>
                    {% for tag in news.tags %}
                      <span
                        class="tag me-2{% if query_lower in tag.denominazione|lower %} headline{% endif %}">{{ tag.denominazione }}</span>
                    {% endfor %}
                    {% if news.files.count %}
                      <i class="fa-solid fa-paperclip brown me-1"></i>
                      <span class="fw-700 me-1">{{ news.files.count }}</span>
                      {% if news.files.count > 1 %}
                        allegati
                      {% else %}
                        allegato
                      {% endif %}
                    {% endif %}
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

infoparlamento/templates/newsletter/newsletter_change_form.html
{% extends 'admin/change_form.html' %}
{% load users_extras %}

{% block submit_buttons_top %}
  {{ block.super }}
  {% if original.sent_at is None %}
    {% if request.user|has_group:"Redattori" or request.user|has_group:"Amministratori" or request.user.is_superuser %}
      <div class="submit-row" style="display: flex; justify-content: flex-end;">
          <input type="submit" value="Invia anteprima" name="_send-preview" title="Inviati un'anteprima">
          {% if request.user.is_superuser or request.user|has_group:"Amministratori" %}
          <input
            type="submit" value="Invia newsletter" name="_send-newsletter" title="Invia la newsletter a tutti"
            style="background-color: darkorange!important;"
          >
          {% endif %}
      </div>
    {% endif %}
  {% endif %}
{% endblock %}